### ISSUE TITLE
how to fix Successfully initialized wpa_supplicant wlan0: No network configuration found for the current AP

### ISSUE THREAD

**Issue by Mrvu182hp** [adde88/krackattacks-pineapple#2]
please help me how to fix problem 
output

~/krackattacks-pineapple/krackattack $ sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf
Successfully initialized wpa_supplicant
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=b4:ee:b4:4c:1f:d4 reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
wlan0: No network configuration found for the current AP
wlan0: CTRL-EVENT-DISCONNECTED bssid=18:d0:71:5d:3a:bf reason=3 locally_generated=1
wlan0: CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
^Cnl80211: deinit ifname=wlan0 disabled_11b_rates=0
thank a lot

**Comment by adde88** [comment]
Try forcing wpa_supplicant to be more verbose in the output.
Adding **-d** as an argument should increase debugging verbosity (**-dd** even more)

**Comment by adde88** [comment]
You seem to be launching **wpa_supplicant** on your PC. _(sudo doesn't exist on the pineapples)_
This entire repository should be stored on the Pineapple and launched on the Pineapple, for example by using a SSH connection.
